
package sd.clt.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "PictureExistsException", targetNamespace = "http://srv.sd/")
public class PictureExistsException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PictureExistsException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public PictureExistsException_Exception(String message, PictureExistsException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public PictureExistsException_Exception(String message, PictureExistsException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: sd.clt.ws.PictureExistsException
     */
    public PictureExistsException getFaultInfo() {
        return faultInfo;
    }

}
